// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import {
    envConfig 
} from "./src/modules/env"
import "dotenv/config"
import {
    defineConfig 
} from "prisma/config"

export default defineConfig({
    schema: "prisma/schema.prisma",
    migrations: {
        path: "prisma/migrations",
    },
    datasource: {
        url: envConfig().databases.postgresql.primary.url,
    },
})
